version: "3.8"
services:
    drone:
        image: docker.io/drone/drone:latest
        ports:
        - "9000:80"
        environment:
        - TZ=Asia/Shanghai
        - DRONE_SERVER_HOST=192.168.56.102:9000
        - DRONE_SERVER_PROTO=http
        - DRONE_RPC_SECRET=55cc8950dbf26ca82d740d344e5196fd
        - DRONE_COOKIE_SECRET=e8206356c843d81e05ab6735e7ebf075
        - DRONE_COOKIE_TIMEOUT=720h
        - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
        - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
        - DRONE_GITEA_SERVER=http://192.168.56.102:3000/
        - DRONE_LOGS_DEBUG=true
        - DRONE_CRON_DISABLED=true
        restart: always
        volumes:
        - /data/drone/data:/data:z
        networks:
        - default
        - gitea
    runner:
        image: docker.io/drone/drone-runner-ssh
        ports:
        - "9001:3000"
        depends_on:
        - drone
        environment:
        - DRONE_RPC_HOST=192.168.56.102:9000
        - DRONE_RPC_PROTO=http
        - DRONE_RPC_SECRET=55cc8950dbf26ca82d740d344e5196fd
        - DRONE_DEBUG=true
        - DRONE_RUNNER_CAPACITY=2
        - DRONE_RUNNER_NAME=drone-runner-ssh
        networks:
        - default
        - gitea
    docker:
        image: docker.io/docker:dind
        ports:
        - "9002:9002"
        depends_on:
        - drone
        privileged: true
        volumes:
        - /data/drone/docker:/var/lib/docker:z

networks:
    default:
        external: false
    gitea:
        external:
            name: gitea
    docker:
        external: false
