version: "3.8"
services:
    drone:
        image: docker.io/drone/drone:latest
        ports:
        - "9000:80"
        environment:
        - DRONE_SERVER_HOST=192.168.56.102:9000
        - DRONE_SERVER_PROTO=http
        - DRONE_RPC_SECRET=bea26a2221fd8090ea38720fc445eca6
        - DRONE_COOKIE_SECRET=e8206356c843d81e05ab6735e7ebf075
        - DRONE_COOKIE_TIMEOUT=720h
        - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
        - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
        - DRONE_GITEA_SERVER=http://192.168.56.102:3000
        - DRONE_LOGS_DEBUG=true
        - DRONE_CRON_DISABLED=true
        restart: always
        volumes:
        - /data/drone/data:/data:z
        networks:
        - default
        - gitea
        - docker
    docker:
        image: docker.io/docker:dind
        ports:
        - "9001:9001"
        volumes:
        - .env:/opt/.env:z
        - /data/drone/docker:/var/lib/docker:z
        restart: always
        env_file:
        - .env
        privileged: true
        networks:
        - docker
        - default
#    runner:
#        image: docker.io/drone/drone-runner-docker:linux-amd64
#        ports:
#        - "9001:9001"
#        environment:
#        - DRONE_RPC_HOST=drone
#        - DRONE_RPC_PROTO=http
#        - DRONE_RPC_SECRET=bea26a2221fd8090ea38720fc445eca6
#        networks:
#        - default
#        - gitea
#        - docker

networks:
    default:
        external: false
    gitea:
        external:
            name: gitea
    docker:
        external: false
