version: "3"
services:
  xxljob-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: xxljob_server
    restart: unless-stopped
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://xxljob_mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=xxljob --spring.datasource.password=xxljob --xxl.job.accessToken=0123456789abcdefg"
    logging:
      options:
        max-size: "5M"
        max-file: "5"
      driver: json-file
    volumes:
      - /data/xxljob/logs:/data/applogs
    ports:
      - "8080:8080"
    depends_on:
      - xxljob-mysql
    networks:
      - xxljob-net

  xxljob-executor:
    image: tandaly/xxl-job-executor:2.3.0
    container_name: xxljob_executor
    restart: unless-stopped
    ports:
      - 9999:9999
      - 8081:8081
    depends_on:
      - xxljob-admin
    environment:
      PARAMS: "--xxl.job.admin.addresses=http://${XXL_JOB_ADMIN_HOST}:8080/xxl-job-admin --xxl.job.accessToken=0123456789abcdefg"
    networks:
      - xxljob-net

  xxljob-mysql:
    image: mysql:5.7
    container_name: xxljob_mysql
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "xxl_job"
      MYSQL_USER: "xxljob"
      MYSQL_PASSWORD: "xxljob"
    ports:
      - 3306:3306
    volumes:
      - /data/xxljob/mysql/my.cnf:/root/.my.cnf
      - /data/xxljob/mysql/data:/var/lib/mysql
      - /data/xxljob/mysql/logs:/var/log/mysql
      - /data/xxljob/mysql/init:/docker-entrypoint-initdb.d/
    networks:
      - xxljob-net

networks:
  xxljob-net:
