CREATE SCHEMA INVENTORY;

CREATE TABLE INVENTORY.ROCKET(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   ADDRESS        CHAR(50),
   SALARY         REAL
);
