version: "3"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd_server
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_CONFIG_FILE=/etcd_conf/etcd.conf.yml
    volumes:
      - /data/etcd/data:/opt/etcd
      - /data/etcd/conf/etcd.conf.yml:/etcd_conf/etcd.conf.yml
    ports:
      - 2379:2379
      - 2380:2380
