version: '3'

services:
  master:
    image: bitnami/mariadb:latest
    container_name: mariadb_master
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /data/mariadb/master/data:/bitnami/mariadb/data
      - /data/mariadb/master/log:/bitnami/mariadb/log
      - /data/mariadb/master/conf/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - /data/mariadb/master/init:/docker-entrypoint-initdb.d
    environment:
      - BITNAMI_DEBUG=true
      - MARIADB_ROOT_PASSWORD=my_root_password
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_general_ci
      - MARIADB_DATABASE=my_database
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  slave1:
    image: bitnami/mariadb:latest
    container_name: mariadb_slave1
    restart: always
    ports:
#      - 3306
      - 3307:3306
    volumes:
      - /data/mariadb/slave1/data:/bitnami/mariadb/data
      - /data/mariadb/slave1/log:/bitnami/mariadb/log
      - /data/mariadb/slave1/conf/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - /data/mariadb/slave1/init:/docker-entrypoint-initdb.d
    environment:
      - BITNAMI_DEBUG=true
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_general_ci
      - MARIADB_MASTER_HOST=master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=my_root_password
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      - master

  slave2:
    image: bitnami/mariadb:latest
    container_name: mariadb_slave2
    restart: always
    ports:
#      - 3306
      - 3308:3306
    volumes:
      - /data/mariadb/slave2/data:/bitnami/mariadb/data
      - /data/mariadb/slave2/log:/bitnami/mariadb/log
      - /data/mariadb/slave2/conf/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - /data/mariadb/slave2/init:/docker-entrypoint-initdb.d
    environment:
      - BITNAMI_DEBUG=true
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_general_ci
      - MARIADB_MASTER_HOST=master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=my_root_password
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      - master

  proxysql:
    image: severalnines/proxysql:2.2.0
    container_name: mariadb_proxysql
    ports:
      - 6033:6033
      - 6032:6032
    restart: unless-stopped
    volumes:
      - /data/mariadb/proxysql/data:/var/lib/proxysql
      - /data/mariadb/proxysql/conf/proxysql.cnf:/etc/proxysql.cnf
