version: '3'

services:
  mysql:
    image: bitnami/mysql:8.0
    container_name: mysql8_single
    ports:
      - 3306:3306
    volumes:
      - /data/mysql/data:/bitnami/mysql/data
      - /data/mysql/log:/bitnami/mysql/log
      - /data/mysql/conf/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
    environment:
      - BITNAMI_DEBUG=true
      - MYSQL_ROOT_PASSWORD=my_root_password
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_general_ci
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
