version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - 80:80
    privileged: true
    environment:
      - TZ="Asia/Shanghai"
    volumes:
      - /data/nginx/html:/usr/share/nginx/html
      - /data/nginx/log:/var/log/nginx
      - /data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/conf.d:/etc/nginx/conf.d
