version: '3'
services:
  postgres:
    image: postgres:13
    container_name: sonarqube_postgres
    volumes:
      - /data/sonarqube/postgres:/var/lib/postgresql
      - /data/sonarqube/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_USER=sonarqube
      - POSTGRES_DB=sonarqube

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube_server
    ports:
      - 80:9000
    volumes:
      - /data/sonarqube/data:/opt/sonarqube/data
      - /data/sonarqube/logs:/opt/sonarqube/logs
      - /data/sonarqube/extensions:/opt/sonarqube/extensions
    depends_on:
      - postgres
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonarqube
      - SONAR_JDBC_PASSWORD=sonarqube
