version: "3"
services:
  wiki:
    image: docker.io/requarks/wiki:2
    container_name: wikijs_server
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=wiki
      - DB_USER=wikijs
      - DB_PASS=wikijsrocks
      - TZ=Asia/Shanghai
    restart: unless-stopped
    ports:
      - "80:3000"
    depends_on:
      - db

  db:
    image: docker.io/postgres:13
    container_name: wikijs_db
    restart: always
    environment:
      - POSTGRES_USER=wikijs
      - POSTGRES_PASSWORD=wikijsrocks
      - POSTGRES_DB=wiki
      - TZ=Asia/Shanghai
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - /data/wikijs/postgres/data:/var/lib/postgresql/data:z
