version: "3"
services:
  confluence:
    image: atlassian/confluence:6.14.1
    container_name: confluence_server
    restart: unless-stopped
    volumes:
      - /data/confluence/data:/var/atlassian/application-data/confluence
    ports:
      - 8090:8090
      - 8091:8091
