version: "3"
services:
  meilisearch:
    image: getmeili/meilisearch:v0.20.0
    container_name: meilisearch_server
    restart: unless-stopped
    environment:
      - MEILI_ENV=production               # default: development, can visit web interface: 127.0.0.1:7700
      - MEILI_MASTER_KEY=meili-master-key  # in production env, search apis provide it.
    volumes:
      - /data/meilisearch/data:/data.ms
    ports:
      - 7700:7700
    logging:
      options:
        max-size: "5M"
        max-file: "5"
      driver: json-file
