version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis_server
    restart: unless-stopped
    ports:
      - 6379:6379
    privileged: true
    environment:
      - TZ="Asia/Shanghai"
    volumes:
      - /data/redis/single/conf:/etc/redis
      - /data/redis/single/data:/data
    command: ["redis-server", "/etc/redis/redis.conf", "--requirepass '123456'"]
