version: "3"
services:
  minio:
    image: minio/minio
    container_name: minio_server
    restart: unless-stopped
    environment:
      - MINIO_DOMAIN=mydomain.example
      - MINIO_REGION_NAME=myregion-01
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    logging:
      options:
        max-size: "5M"
        max-file: "5"
      driver: json-file
    volumes:
      - /data/minio/data:/data
      - /data/minio/conf:/root/.minio
    command: server /data
    ports:
      - "9000:9000"
